[package]
name = "cgroupv2-rs"
version = "0.1.0"
authors = ["magicalne"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
users = "0.10"
libc = "0.2.80"
thiserror = "1.0.20"

[dev-dependencies]
rusty-fork = "0.3.0"
